language: rust
rust:
- stable
sudo: false
os:
- linux
addons:
  apt:
    packages:
    - gcc-mingw-w64-i686
    - gcc-mingw-w64-x86-64
    - libudev-dev
cache:
  directories:
  - "$HOME/.cargo"
  - target
matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly
env:
  matrix:
  - EXE_SUFFIX=-linux64
  - CARGO_TARGET=i686-pc-windows-gnu
    EXE_SUFFIX=-win32
  - CARGO_TARGET=x86_64-pc-windows-gnu
    EXE_SUFFIX=-win64
  global:
  - CARGO_QUIET=
  - CARGO_INCREMENTAL=0
  - secure: G02O/+VD2x77E9bhyHVYqIDqZUuSuOlR1tZ/tOcTbwnXTe/VIdqlML8eMDsPtHSKhIQhAX2zyet0jDFUqpIZSYxTQfi2xE8CZ7Lqser48j7jOHhkaWiiRrWPuzi0UDrynvsJUeopMXo1r3uOVlnmiff5DfPxBOkviAD/qi6/eb9qnncHEjsYFsW+dw9KCvKpKoHACYw7Brpm4w2wPnAh0cUod+CgjNPWP4uV/rLuq/R7oWOa24exUxgHtQok2/WN6HJPQstaoEbrOIY/PbILJ3PpXXuv1bEOXVs6X6ArGj+bNyyWWRTlQ9AlA0ErI1lAit0/kFESq99WtLwrYe21+EpBszcqJqZFRm5vVqDh4h6x6l6pH+jbE9lXEo/OvbLmcLgGKruJkey0xrQemcJIzlAPftysthRxJibX83lDf2dO/Y2CLn18nmcKa945Bat1CJWYP0GCHC3kLttyTeIXUnOb4uZd2IfkAejHV4bt5+5bqXqE5+ZqUrlS0COCO0fpe882jZmuJHZabHWIMpeSAJxbxhy1ES1DlABm2uFW9C19XDuRaVe9yj4NNyF41TkHoqy3xVKxRMvECUtEvzS51l/50m2z0h4uzAQ89kDiQzn1YVob+YHRrHp1Xi4IXsRSmQALFkl2Anof0Jv0Orn1o2fqpAubXlLdyN0bh/9AptU=
  - secure: lb5GE9jjhqG9r2XgFIcGF5xR8SPUOFqZ3QtycWs1uL5TchlfKRASSk7IOv+BbU1bn9b9LpxQVAqosyIP723UIVDIppMB7UwutMHd7nU3l3BojhX4ZJ3dPYA1afBqgEyfkNXHNVbYSF7fojum39EfTmh7uew8s0UU/lrNbfVC0kYiCUuUKhQziwdikdHo6DkakDALducP481+Dq1BE2j8OK7ArzY/YOd/RgLMxJItnyBJyQDXM7Jg0Uy0etgqSxYSYBA/24yr4lX12m6R7QUnPI1MtJzUkEuoRIRTnsvD8KqavFugmsQQRg45DiQCOOOqLFtm+27wBRsv67VznwDmrL+mi9Cyeznt8jvDNMY7/O2eqe1gjg267+y0PHETrBriwGBJKueYPUr9oRHWwiOgDPYoHL01sOJoV7sRMjo2117mavWIgPKRECzi50CkZUPpVPUzTM/v0fRwauI4U8GuTC2YIFsscIzkUhIirhYLsttYTwc03EdfNrvmQpDliAix0/eDi7OJD7i2bmzXlpFmIfL7CIBo9RZ10DfRyd3I6kAO+GdpIy2w0yTqnHYU85G3EpBHShBGyauetv3rEQV40Nlj0LTSpU2CjCG4MJqm7OUJe9/LKz3rDV1Cn0zV2L7qTkB7Va6BIbfx4hzBWiFK8lfZXSNzepAW/hQ7K/08rFU=
before_install:
- curl -L https://github.com/arcnmx/ci/archive/0.2.tar.gz | tar -xzC $HOME && . $HOME/ci-0.2/src
script:
- cargo build
deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GH_TOKEN"
  file:
  - "$CARGO_TARGET_DIR/$CARGO_TARGET/release/ddcset-$TRAVIS_TAG$EXE_SUFFIX$CI_SUFFIX_BIN"
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_RUST_VERSION = stable"
before_deploy:
- cargo build --release
- strip -o "$CARGO_TARGET_DIR/$CARGO_TARGET/release/ddcset-$TRAVIS_TAG$EXE_SUFFIX$CI_SUFFIX_BIN" "$CARGO_TARGET_DIR/$CARGO_TARGET/release/ddcset$CI_SUFFIX_BIN"
- |
  if [[ -z "$CARGO_TARGET" ]]; then
    cargo package
  fi
after_deploy:
- |
  if [[ -z "$CARGO_TARGET" ]]; then
    cargo publish
  fi
